from sympy import symbols, diff, sin, cos, tan
x = symbols('x')
y = symbols('y')
z = symbols('z')
vx = symbols('vx')
vy = symbols('vy')
vz = symbols('vz')
psi = symbols('psi')
theta = symbols('theta')
gamma = symbols('gamma')
wx = symbols('wx')
wy = symbols('wy')
wz = symbols('wz')

Fx = symbols('Fx')
Fy = symbols('Fy')
Fz = symbols('Fz')
Mx = symbols('Mx')
My=symbols('My')
Mz=symbols('Mz')
Ix=symbols('Ix')
Iy=symbols('Iy')
Iz=symbols('Iz')
m = symbols('m')


func1 = vx * cos(theta) * cos(psi) + vy * (sin(gamma) * sin(psi) - cos(gamma) * sin(theta) * cos(psi)) + vz * (cos(gamma) * sin(psi) + sin(gamma) * sin(theta) * cos(psi))

print('A1_1 = ', func1.diff(x))
print('A1_2 = ', func1.diff(y))
print('A1_3 = ', func1.diff(z))
print('A1_4 = ', func1.diff(vx))
print('A1_5 = ', func1.diff(vy))
print('A1_6 = ', func1.diff(vz))
print('A1_7 = ', func1.diff(psi))
print('A1_8 = ', func1.diff(theta))
print('A1_9 = ', func1.diff(gamma))
print('A1_10 = ', func1.diff(wx))
print('A1_11 = ', func1.diff(wy))
print('A1_12 = ', func1.diff(wz))

func2 = vx * sin(theta) + vy * cos(gamma) * cos(theta) - vz * (sin(gamma) * cos(theta))

print('A2_1 = ', func2.diff(x))
print('A2_2 = ', func2.diff(y))
print('A2_3 = ', func2.diff(z))
print('A2_4 = ', func2.diff(vx))
print('A2_5 = ', func2.diff(vy))
print('A2_6 = ', func2.diff(vz))
print('A2_7 = ', func2.diff(psi))
print('A2_8 = ', func2.diff(theta))
print('A2_9 = ', func2.diff(gamma))
print('A2_10 = ', func2.diff(wx))
print('A2_11 = ', func2.diff(wy))
print('A2_12 = ', func2.diff(wz))

func3 = -vx * cos(theta) * sin(psi) + vy * (sin(gamma) * cos(psi) + cos(gamma) * sin(theta) * sin(psi)) + vz * (cos(gamma) * cos(psi) - sin(gamma) * sin(theta) * sin(psi))

print('A3_1 = ', func3.diff(x))
print('A3_2 = ', func3.diff(y))
print('A3_3 = ', func3.diff(z))
print('A3_4 = ', func3.diff(vx))
print('A3_5 = ', func3.diff(vy))
print('A3_6 = ', func3.diff(vz))
print('A3_7 = ', func3.diff(psi))
print('A3_8 = ', func3.diff(theta))
print('A3_9 = ', func3.diff(gamma))
print('A3_10 = ', func3.diff(wx))
print('A3_11 = ', func3.diff(wy))
print('A3_12 = ', func3.diff(wz))

func4 = Fx / m + vy * wz - vz * wy

print('A4_1 = ', func4.diff(x))
print('A4_2 = ', func4.diff(y))
print('A4_3 = ', func4.diff(z))
print('A4_4 = ', func4.diff(vx))
print('A4_5 = ', func4.diff(vy))
print('A4_6 = ', func4.diff(vz))
print('A4_7 = ', func4.diff(psi))
print('A4_8 = ', func4.diff(theta))
print('A4_9 = ', func4.diff(gamma))
print('A4_10 = ', func4.diff(wx))
print('A4_11 = ', func4.diff(wy))
print('A4_12 = ', func4.diff(wz))

func5 = Fy / m + vz * wx - vx * wz

print('A5_1 = ', func5.diff(x))
print('A5_2 = ', func5.diff(y))
print('A5_3 = ', func5.diff(z))
print('A5_4 = ', func5.diff(vx))
print('A5_5 = ', func5.diff(vy))
print('A5_6 = ', func5.diff(vz))
print('A5_7 = ', func5.diff(psi))
print('A5_8 = ', func5.diff(theta))
print('A5_9 = ', func5.diff(gamma))
print('A5_10 = ', func5.diff(wx))
print('A5_11 = ', func5.diff(wy))
print('A5_12 = ', func5.diff(wz))

func6 = dvzdt = Fz / m + vx * wy - vy * wx

print('A6_1 = ', func6.diff(x))
print('A6_2 = ', func6.diff(y))
print('A6_3 = ', func6.diff(z))
print('A6_4 = ', func6.diff(vx))
print('A6_5 = ', func6.diff(vy))
print('A6_6 = ', func6.diff(vz))
print('A6_7 = ', func6.diff(psi))
print('A6_8 = ', func6.diff(theta))
print('A6_9 = ', func6.diff(gamma))
print('A6_10 = ', func6.diff(wx))
print('A6_11 = ', func6.diff(wy))
print('A6_12 = ', func6.diff(wz))

func7 = 1/cos(theta) * (wy * cos(gamma) - wz * sin(gamma))

print('A7_1 = ', func7.diff(x))
print('A7_2 = ', func7.diff(y))
print('A7_3 = ', func7.diff(z))
print('A7_4 = ', func7.diff(vx))
print('A7_5 = ', func7.diff(vy))
print('A7_6 = ', func7.diff(vz))
print('A7_7 = ', func7.diff(psi))
print('A7_8 = ', func7.diff(theta))
print('A7_9 = ', func7.diff(gamma))
print('A7_10 = ', func7.diff(wx))
print('A7_11 = ', func7.diff(wy))
print('A7_12 = ', func7.diff(wz))

func8 = wy * sin(gamma) + wz * cos(gamma)

print('A8_1 = ', func8.diff(x))
print('A8_2 = ', func8.diff(y))
print('A8_3 = ', func8.diff(z))
print('A8_4 = ', func8.diff(vx))
print('A8_5 = ', func8.diff(vy))
print('A8_6 = ', func8.diff(vz))
print('A8_7 = ', func8.diff(psi))
print('A8_8 = ', func8.diff(theta))
print('A8_9 = ', func8.diff(gamma))
print('A8_10 = ', func8.diff(wx))
print('A8_11 = ', func8.diff(wy))
print('A8_12 = ', func8.diff(wz))

func9 = wx - tan(theta) * (wy * cos(gamma) - wz * sin(gamma))

print('A9_1 = ', func9.diff(x))
print('A9_2 = ', func9.diff(y))
print('A9_3 = ', func9.diff(z))
print('A9_4 = ', func9.diff(vx))
print('A9_5 = ', func9.diff(vy))
print('A9_6 = ', func9.diff(vz))
print('A9_7 = ', func9.diff(psi))
print('A9_8 = ', func9.diff(theta))
print('A9_9 = ', func9.diff(gamma))
print('A9_10 = ', func9.diff(wx))
print('A9_11 = ', func9.diff(wy))
print('A9_12 = ', func9.diff(wz))

func10 = 1 / Ix * (Mx + (Iy - Iz) * wy * wz)

print('A10_1 = ', func10.diff(x))
print('A10_2 = ', func10.diff(y))
print('A10_3 = ', func10.diff(z))
print('A10_4 = ', func10.diff(vx))
print('A10_5 = ', func10.diff(vy))
print('A10_6 = ', func10.diff(vz))
print('A10_7 = ', func10.diff(psi))
print('A10_8 = ', func10.diff(theta))
print('A10_9 = ', func10.diff(gamma))
print('A10_10 = ', func10.diff(wx))
print('A10_11 = ', func10.diff(wy))
print('A10_12 = ', func10.diff(wz))

func11 = 1 / Iy * (My + (Iz - Ix) * wz * wx)

print('A11_1 = ', func11.diff(x))
print('A11_2 = ', func11.diff(y))
print('A11_3 = ', func11.diff(z))
print('A11_4 = ', func11.diff(vx))
print('A11_5 = ', func11.diff(vy))
print('A11_6 = ', func11.diff(vz))
print('A11_7 = ', func11.diff(psi))
print('A11_8 = ', func11.diff(theta))
print('A11_9 = ', func11.diff(gamma))
print('A11_10 = ', func11.diff(wx))
print('A11_11 = ', func11.diff(wy))
print('A11_12 = ', func11.diff(wz))

func12 = 1 / Iz * (Mz + (Ix - Iy) * wx * wy)

print('A12_1 = ', func12.diff(x))
print('A12_2 = ', func12.diff(y))
print('A12_3 = ', func12.diff(z))
print('A12_4 = ', func12.diff(vx))
print('A12_5 = ', func12.diff(vy))
print('A12_6 = ', func12.diff(vz))
print('A12_7 = ', func12.diff(psi))
print('A12_8 = ', func12.diff(theta))
print('A12_9 = ', func12.diff(gamma))
print('A12_10 = ', func12.diff(wx))
print('A12_11 = ', func12.diff(wy))
print('A12_12 = ', func12.diff(wz))

